[package]
name = "random-question-bot"
version = "0.1.0"
edition = "2018"

[dependencies]
rand = "0.8.5"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.16", features = ["full"] }
